-- MySQL Script generated by MySQL Workbench
-- Tue Nov 11 10:21:57 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema biblioteca_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema biblioteca_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `biblioteca_db` DEFAULT CHARACTER SET utf8mb4 ;
USE `biblioteca_db` ;

-- -----------------------------------------------------
-- Table `biblioteca_db`.`autores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca_db`.`autores` (
  `id_autor` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `nacionalidad` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id_autor`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `biblioteca_db`.`libros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca_db`.`libros` (
  `id_libro` INT(11) NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(255) NOT NULL,
  `anio_publicacion` INT(11) NULL DEFAULT NULL,
  `id_autor` INT(11) NULL,
  PRIMARY KEY (`id_libro`),
  INDEX `id_autor` (`id_autor` ASC),
  CONSTRAINT `libros_ibfk_1`
    FOREIGN KEY (`id_autor`)
    REFERENCES `biblioteca_db`.`autores` (`id_autor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
